title: 'Examples | Modest Maps'
auto: true
server: true
markdown: rdiscount
permalink: /:title.html
server_port: 4001
columnist:
  paths:
  - _posts
baseurl: /mm-examples
rdiscount:
  extensions: [smart]
